--- #YAML:1.0
name:               Image-Hash
version:            0.03
abstract:           An image hashing library to calculate an images average hash, perception hash and difference hash.
author:
    - Runar Buvik (runarb@gmail.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    File::Slurp:   0
    GD:            0
    List::Util:    0
    Test::Simple:  0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
